#!/bin/bash

echo "Instalaciónd e programas para la materia"
if [[ $UID != 0 ]]; then
        echo "No es administrador"
exit 1
else
    echo "Instalaciónd e programas para la materia"
    sudo apt-get install geogebra-classic
fi
