#!/bin/bash
MATERIA="arduino"
echo -en "\033]0;$MATERIA\a"
rm -rf /home/$MATERIA/.local/share/Trash/* 
find /home/$MATERIA/Escritorio/* -user $MATERIA -exec rm -rf {} \;
/usr/bin/progreso &
detach %+ # or % + the number in brackets printed after the above
echo "Instalaciónd e programas para la materia"
if [[ $UID != 0 ]]; then
        echo "No es administrador"
exit 1
else
    sudo /opt/conejo-blanco/effective-spork/Sistema/usuarios/administrador
    sudo /opt/conejo-blanco/effective-spork/Sistema/usuarios/root
    sudo adduser arduino dialout
    echo "┌──Arduino───╸"
    which arduino >/dev/null
    if [ "$?" = "0" ]; then
	    echo "├─arduino:  $(tput setaf 2)OK$(tput sgr 0)"
    else
        echo "├─arduino: $(tput setaf 1)NO$(tput sgr 0)"
        sudo wget https://downloads.arduino.cc/arduino-1.8.10-linux64.tar.xz -O /opt/conejo-blanco/Descargas/parduino-1.8.10-linux64.tar.xz
        sudo tar xvf /opt/conejo-blanco/Descargas/arduino-1.8.10-linux64.tar.xz -C /home/$MATERIA
    fi
    echo "└────────────────────────╸"
fi
killall progreso
