#!/bin/bash
MATERIA="base-datos"

rm -rf /home/$MATERIA/.local/share/Trash/* 

echo "Instalaciónd e programas para la materia"
if [[ $UID != 0 ]]; then
        echo "No es administrador"
exit 1
else
    sudo /opt/conejo-blanco/effective-spork/Sistema/usuarios/administrador
    sudo /opt/conejo-blanco/effective-spork/Sistema/usuarios/root
    which q4wine >/dev/null
    if [ "$?" = "0" ]; then
	    echo "├─Geogebra:  $(tput setaf 2)OK$(tput sgr 0)"
    else
        echo "Instalaciónd e programas para la materia"
        sudo apt-get -y install q4wine
    fi
    echo "┌──Estructuras de persistencia───╸"
    if [ -f /opt/lampp/manager-linux-x64.run ];
    then
        echo "├─XAMPP: $(tput setaf 2)OK$(tput sgr 0)"
    else
        echo "├─XAMPP: $(tput setaf 1)NO$(tput sgr 0)"
    fi
fi
