#!/bin/bash
MATERIA="base-datos"
echo -en "\033]0;$MATERIA\a"
rm -rf /home/$MATERIA/.local/share/Trash/* 
#find /home/$MATERIA/Escritorio/* -user $MATERIA -exec rm -rf {} \;
/usr/bin/progreso &
detach %+ # or % + the number in brackets printed after the above
echo "Instalaciónd e programas para la materia"
if [[ $UID != 0 ]]; then
        echo "No es administrador"
exit 1
else
    sudo /opt/conejo-blanco/effective-spork/Sistema/usuarios/administrador
    sudo /opt/conejo-blanco/effective-spork/Sistema/usuarios/root
    which q4wine >/dev/null
    if [ "$?" = "0" ]; then
	    echo "├─q4wine:  $(tput setaf 2)OK$(tput sgr 0)"
	    if [ ! -f /home/$MATERIA/Escritorio/XAMPP.desktop ];
        then
            sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace $MATERIA XAMPP "/opt/lampp/htdocs/favicon.ico" "pkexec /opt/lampp/manager-linux-x64.run"
        fi
    else
        echo "Instalaciónd e programas para la materia"
        sudo apt-get -y install q4wine
    fi
    echo "┌──XAMPP───╸"
    if [ -f /opt/lampp/manager-linux-x64.run ];
    then
        echo "├─XAMPP: $(tput setaf 2)OK$(tput sgr 0)"
    else
        echo "├─XAMPP: $(tput setaf 1)NO$(tput sgr 0)"
        #https://www.dropbox.com/s/ovd3mtx7ukevts1/com.ubuntu.pkexec.xampp.policy
        sudo wget https://www.dropbox.com/s/ovd3mtx7ukevts1/com.ubuntu.pkexec.xampp.policy -O /usr/share/polkit-1/actions/com.ubuntu.pkexec.xampp.policy
        sudo wget https://www.apachefriends.org/xampp-files/7.2.6/xampp-linux-x64-7.2.6-0-installer.run -O /opt/conejo-blanco/Descargas/xampp-linux-x64-7.2.6-0-installer.run
        sudo chmod +x /opt/conejo-blanco/Descargas/xampp-linux-x64-7.2.6-0-installer.run
        sudo /opt/conejo-blanco/Descargas/xampp-linux-x64-7.2.6-0-installer.run
        sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace $MATERIA XAMPP "/opt/lampp/htdocs/favicon.ico" "pkexec /opt/lampp/manager-linux-x64.run"
    fi
    #which dbeaver >/dev/null
    #if [ "$?" = "0" ]; then
    #	echo "├─dveaber:  $(tput setaf 2)OK$(tput sgr 0)"
    #else
        #echo "├─dbveaver: $(tput setaf 1)NO$(tput sgr 0)"
        #sudo wget hhttps://dbeaver.io/files/6.2.2/dbeaver-ce_6.2.2_amd64.deb -O /opt/conejo-blanco/Descargas/dbeaver-ce_6.2.2_amd64.deb
        #sudo dpkg -i /opt/conejo-blanco/Descargas/dbeaver-ce_6.2.2_amd64.deb
	#sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace $MATERIA dbeaver "/usr/share/dbeaver/dbeaver.png" "/usr/share/dbeaver/dbeaver"
    #fi
fi
killall progreso
