#!/bin/bash
MATERIA="concurrente"
echo -en "\033]0;$MATERIA\a"
rm -rf /home/$MATERIA/.local/share/Trash/* 
find /home/$MATERIA/Escritorio/* -user $MATERIA -exec rm -rf {} \;
/usr/bin/progreso &
echo "Instalaciónd e programas para la materia"
if [[ $UID != 0 ]]; then
        echo "No es administrador"
        exit 1
else
    sudo /opt/conejo-blanco/effective-spork/Sistema/usuarios/administrador
    sudo /opt/conejo-blanco/effective-spork/Sistema/usuarios/root    
    #sudo adduser $MATERIA sudo
    #### Aca van las cosas
    mkdir -p /home/$MATERIA/.config/autostart
    which python3 >/dev/null
    if [ "$?" = "0" ]; then
	    echo "├─Python3:  $(tput setaf 2)OK$(tput sgr 0)"
    else
        echo "├─Python3: $(tput setaf 1)NO$(tput sgr 0)"
        sudo apt-get -y install python3
    fi
    sudo apt-get -y install python3-pip
    sudo apt-get -y install python3-tk
    which intellij-idea-community >/dev/null
    if [ "$?" = "0" ];
    then
        echo "├─IDEA: $(tput setaf 2)OK$(tput sgr 0)"
    else
        echo "├─IDEA: $(tput setaf 1)NO$(tput sgr 0)"
	    sudo apt install openjdk-11-jre-headless
		#echo 2 | sudo update-alternatives --config java
	    sudo snap install intellij-idea-community --classic
        sudo cp /snap/intellij-idea-community/427/bin/idea.png /snap/idea.png
	    sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace "$MATERIA" "IDEA" "/snap/intellij-idea-community/427/bin/idea.png" "intellij-idea-community"
    fi
    echo "└────────────────────────╸"
    if [ ! -f /home/$MATERIA/Escritorio/IDEA.desktop ];
    then
    	sudo cp /snap/intellij-idea-community/323/bin/idea.png /snap/idea.png
        sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace "$MATERIA" "IDEA" "/snap/intellij-idea-community/427/bin/idea.png" "intellij-idea-community"
    fi

fi
killall progreso
