#!/bin/bash
MATERIA="estadistica"

rm -rf /home/$MATERIA/.local/share/Trash/* 

echo "Instalaciónd e programas para la materia"
if [[ $UID != 0 ]]; then
        echo "No es administrador"
exit 1
else
    sudo /opt/conejo-blanco/effective-spork/Sistema/usuarios/administrador
    sudo /opt/conejo-blanco/effective-spork/Sistema/usuarios/root
    which q4wine >/dev/null
    if [ "$?" = "0" ]; then
	    echo "├─Geogebra:  $(tput setaf 2)OK$(tput sgr 0)"
    else
        echo "Instalaciónd e programas para la materia"
        sudo apt-get -y install q4wine
    fi
fi
