#!/bin/bash
MATERIA="estruc-datos"
echo -en "\033]0;$MATERIA\a"
rm -rf /home/$MATERIA/.local/share/Trash/* 
find /home/$MATERIA/Escritorio/* -user $MATERIA -exec rm -rf {} \;
/usr/bin/progreso &
detach %+ # or % + the number in brackets printed after the above
echo "Instalaciónd e programas para la materia"
if [[ $UID != 0 ]]; then
        echo "No es administrador"
exit 1
else
    sudo /opt/conejo-blanco/effective-spork/Sistema/usuarios/administrador
    sudo /opt/conejo-blanco/effective-spork/Sistema/usuarios/root
    echo "┌──Estructura de datos───╸"
    which eclipse >/dev/null
    if [ "$?" = "0" ]; then
	    echo "├─Eclipse:  $(tput setaf 2)OK$(tput sgr 0)"
    else
        echo "├─Eclipse: $(tput setaf 1)NO$(tput sgr 0)"
        sudo snap install --classic eclipse
        pkexec bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace $MATERIA "eclipse_eclipse" "/snap/eclipse/40/icon.xpm" "env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/eclipse_eclipse.desktop /snap/bin/eclipse %U"
    fi
    if [ -f /home/estruc-datos/anaconda3/bin/anaconda-navigator ];
    then
        echo "├─Anaconda: $(tput setaf 2)OK$(tput sgr 0)"
	if [ ! -f /home/$MATERIA/Escritorio/ANACONDA.desktop ];
        then
            sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace $MATERIA "ANACONDA" "/home/$MATERIA/anaconda3/lib/python3.7/site-packages/anaconda_navigator/static/images/anaconda-icon-256x256.png" "/home/$MATERIA/anaconda3/bin/anaconda-navigator"
        fi
    else
        echo "├─Anaconda: $(tput setaf 1)NO$(tput sgr 0)"
        sudo wget https://repo.anaconda.com/archive/Anaconda3-2019.07-Linux-x86_64.sh -O /opt/conejo-blanco/Descargas/Anaconda3-2019.07-Linux-x86_64.sh
        sudo bash /opt/conejo-blanco/Descargas/Anaconda3-2019.07-Linux-x86_64.sh -b -p /home/$MATERIA/anaconda3
        sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace $MATERIA "ANACONDA" "/home/$MATERIA/anaconda3/lib/python3.7/site-packages/anaconda_navigator/static/images/anaconda-icon-256x256.png" "/home/$MATERIA/anaconda3/bin/anaconda-navigator"
    fi
    echo "└────────────────────────╸"
    #conda install python-graphviz
    #su $MATERIA
    /home/estruc-datos/anaconda3/bin/conda install -y python-graphviz
    fi
    which code >/dev/null
    if [ "$?" = "0" ]; then
    	echo "├─Code Studio:  $(tput setaf 2)OK$(tput sgr 0)"
    else
        echo "├─Code Studio: $(tput setaf 1)NO$(tput sgr 0)"
        sudo wget https://az764295.vo.msecnd.net/stable/c7d83e57cd18f18026a8162d042843bda1bcf21f/code_1.35.1-1560350270_amd64.deb -O /opt/conejo-blanco/Descargas/code_1.35.1-1560350270_amd64.deb
        sudo dpkg -i /opt/conejo-blanco/Descargas/code_1.35.1-1560350270_amd64.deb
        sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace "$MATERIA" "code" "com.visualstudio.code" "/usr/share/code/code --unity-launch %F"
    fi

killall progreso
