#!/bin/bash

MATERIA="martin-vernengo"
echo -en "\033]0;$MATERIA\a"
rm -rf /home/$MATERIA/.local/share/Trash/* 
find /home/$MATERIA/Escritorio/* -user $MATERIA -exec rm -rf {} \;
/usr/bin/progreso &
detach %+ # or % + the number in brackets printed after the above
echo "Instalaciónd e programas para la materia"
if [[ $UID != 0 ]]; then
        echo "No es administrador"
exit 1
else
    sudo /opt/conejo-blanco/effective-spork/Sistema/usuarios/administrador
    sudo /opt/conejo-blanco/effective-spork/Sistema/usuarios/root
    sudo passwd -d usuario-invitado
    sudo passwd -d nuevos-entornos
    sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace $MATERIA "firefox" "firefox" "firefox --private-window http://unahur.edu.ar"
    which google-chrome-stable >/dev/null
    if [ "$?" = "0" ]; then
    	echo "├─Chrome:  $(tput setaf 2)OK$(tput sgr 0)"
    else
        echo "├─Chrome: $(tput setaf 1)NO$(tput sgr 0)"
        sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O /opt/conejo-blanco/Descargas/google-chrome-stable_current_amd64.deb
        sudo dpkg -i /opt/conejo-blanco/Descargas/google-chrome-stable_current_amd64.deb
    fi
    #if [ ! -f /home/$MATERIA/Escritorio/google-chrome.desktop ];
    #then
        sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace $MATERIA "google-chrome" "google-chrome" "google-chrome --password-store=basic --incognito http://unahur.edu.ar"
    #fi
    
    if [ -f /home/$MATERIA/Logisim/logisim-generic-2.7.1.jar ];
    then
        echo "├─Logisim: $(tput setaf 2)OK$(tput sgr 0)"
        if [ ! -f /home/$MATERIA/Escritorio/logisim.desktop ];
        then
            sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace "$MATERIA" "logisim" "/home/$MATERIA/Logisim/Logisim-icon.png" "/usr/lib/jvm/java-8-openjdk-amd64/bin/java -jar /home/$MATERIA/Logisim/logisim-generic-2.7.1.jar" 
        fi
        if [ ! -f /home/$MATERIA/Logisim/Logisim-icon.png ];
        then
            wget https://www.dropbox.com/s/fwl7h6g5avnfven/Logisim-icon.png -O /home/$MATERIA/Logisim/Logisim-icon.png
            sudo chmod 555 /home/$MATERIA/Logisim/Logisim-icon.png
            sudo chmod 755 /home/$MATERIA/Logisim/logisim-generic-2.7.1.jar
        fi
    else
        echo "├─Logisim: $(tput setaf 1)NO$(tput sgr 0)"
   	    if [ ! -d /home/$MATERIA/Logisim/ ];
            then
                sudo mkdir /home/$MATERIA/Logisim
                sudo chown $MATERIA /home/$MATERIA/Logisim
                sudo chgrp $MATERIA /home/$MATERIA/Logisim
        fi 
        wget https://razaoinfo.dl.sourceforge.net/project/circuit/2.7.x/2.7.1/logisim-generic-2.7.1.jar -O /home/$MATERIA/Logisim/logisim-generic-2.7.1.jar
        sudo chmod 755 /home/$MATERIA/Logisim/logisim-generic-2.7.1.jar
        wget https://www.dropbox.com/s/fwl7h6g5avnfven/Logisim-icon.png -O /home/$MATERIA/Logisim/Logisim-icon.png
        sudo chmod 555 /home/$MATERIA/Logisim/Logisim-icon.png
        sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace "$MATERIA" "logisim" "/home/$MATERIA/Logisim/Logisim-icon.png" "/usr/lib/jvm/java-8-openjdk-amd64/bin/java -jar /home/$MATERIA/Logisim/logisim-generic-2.7.1.jar"
    fi
    
    if [ -f /home/$MATERIA/Logisim/logisim-evolution.jar ];
    then
        echo "├─logisim-evolution: $(tput setaf 2)OK$(tput sgr 0)"
        if [ ! -f /home/$MATERIA/Escritorio/logisim-evolution.desktop ];
        then
            sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace "$MATERIA" "logisim-evolution" "/home/$MATERIA/logisim-evolution/logisim-icon-256.png" "/usr/lib/jvm/java-8-openjdk-amd64/bin/java -jar /home/$MATERIA/logisim-evolution/logisim-evolution.jar" 
        fi
        if [ ! -f /home/$MATERIA/logisim-evolution/logisim-icon-256.png ];
        then
            wget https://dashboard.snapcraft.io/site_media/appmedia/2021/12/logisim-icon-256.png -O /home/$MATERIA/logisim-evolution/logisim-icon-256.png
            sudo chmod 555 /home/$MATERIA/logisim-evolution/logisim-icon-256.png
            sudo chmod 755 /home/$MATERIA/logisim-evolution/logisim-evolution.jar
        fi
    else
        echo "├─logisim-evolution: $(tput setaf 1)NO$(tput sgr 0)"
   	    if [ ! -d /home/$MATERIA/logisim-evolution/ ];
            then
                sudo mkdir /home/$MATERIA/logisim-evolution
                sudo chown $MATERIA /home/$MATERIA/logisim-evolution
                sudo chgrp $MATERIA /home/$MATERIA/logisim-evolution
        fi 
        wget https://razaoinfo.dl.sourceforge.net/project/logisimevolution/logisim-evolution.jar -O /home/$MATERIA/logisim-evolution/logisim-evolution.jar
        wget https://dashboard.snapcraft.io/site_media/appmedia/2021/12/logisim-icon-256.png -O /home/$MATERIA/logisim-evolution/logisim-icon-256.png
        sudo chmod 555 /home/$MATERIA/logisim-evolution/logisim-icon-256.png
        sudo chmod 755 /home/$MATERIA/logisim-evolution/logisim-evolution.jar
        sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace "$MATERIA" "logisim-evolution" "/home/$MATERIA/logisim-evolution/logisim-icon-256.png" "/usr/lib/jvm/java-8-openjdk-amd64/bin/java -jar /home/$MATERIA/logisim-evolution/logisim-evolution.jar"
    fi

fi
killall progreso
