#!/bin/bash
MATERIA="objetos-2"
echo -en "\033]0;$MATERIA\a"
rm -rf /home/$MATERIA/.local/share/Trash/* 
find /home/$MATERIA/Escritorio/* -user $MATERIA -exec rm -rf {} \;
echo "Instalaciónd e programas para la materia"
/usr/bin/progreso &
detach %+ # or % + the number in brackets printed after the above
if [[ $UID != 0 ]]; then
        echo "No es administrador"
exit 1
else
    sudo /opt/conejo-blanco/effective-spork/Sistema/usuarios/administrador
    sudo /opt/conejo-blanco/effective-spork/Sistema/usuarios/root
    echo "┌──Objetos 2───╸"
    mvn --version >/dev/null
    if [ "$?" = "0" ]; then
	    echo "├─Maven:  $(tput setaf 2)OK$(tput sgr 0)"
    else
        echo "├─Maven: $(tput setaf 1)NO$(tput sgr 0)"
        sudo apt-get install -y maven
    fi
    	#if [ -f /opt/idea-IC-191.6183.87/bin/idea.sh ];
    which intellij-idea-community >/dev/null
    if [ "$?" = "0" ];
    then
        echo "├─IDEA: $(tput setaf 2)OK$(tput sgr 0)"
    else
        echo "├─IDEA: $(tput setaf 1)NO$(tput sgr 0)"
        	#curl --version
        	#if [ "$?" = "0" ]; then
		#        echo "si, esta instalado, ahora lo voy a usar."
        	#else
        	#    sudo apt-get -y install -y curl
        	#fi        
        	#sudo curl -o /opt/conejo-blanco/Descargas/ideaIC-2019.1.tar.gz https://download-cf.jetbrains.com/idea/ideaIC-2019.1.tar.gz
        	#sudo tar xvzf /opt/conejo-blanco/Descargas/ideaIC-2019.1.tar.gz -C /opt
	sudo apt install openjdk-11-jre-headless
		#echo 2 | sudo update-alternatives --config java
	sudo snap install intellij-idea-community --classic
	
        	#sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace "$MATERIA" "IDEA" "//opt/idea-IC-191.6183.87/bin/idea.svg" ""/opt/idea-IC-191.6183.87/bin/idea.sh" %f"
        sudo cp /snap/intellij-idea-community/323/bin/idea.png /snap/idea.png
	sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace "$MATERIA" "IDEA" "/snap/idea.png" "intellij-idea-community"
    fi
    echo "└────────────────────────╸"
    if [ ! -f /home/$MATERIA/Escritorio/IDEA.desktop ];
    then
    	sudo cp /snap/intellij-idea-community/323/bin/idea.png /snap/idea.png
        sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace "$MATERIA" "IDEA" "/snap/idea.png" "intellij-idea-community"
    fi
    
    which code >/dev/null
    if [ "$?" = "0" ]; then
	    echo "├─Code Studio:  $(tput setaf 2)OK$(tput sgr 0)"
        if [ ! -f /home/$MATERIA/Escritorio/code.desktop ];
        then
            sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace "$MATERIA" "code" "com.visualstudio.code" "/usr/share/code/code --unity-launch %F"
        fi
    else
        echo "├─Code Studio: $(tput setaf 1)NO$(tput sgr 0)"
        if [ ! -f /opt/conejo-blanco/Descargas/code_1.35.1-1560350270_amd64.deb ];
        then
            sudo wget https://az764295.vo.msecnd.net/stable/c7d83e57cd18f18026a8162d042843bda1bcf21f/code_1.35.1-1560350270_amd64.deb -O /opt/conejo-blanco/Descargas/code_1.35.1-1560350270_amd64.deb
        fi
        sudo dpkg -i /opt/conejo-blanco/Descargas/code_1.35.1-1560350270_amd64.deb
        sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace "$MATERIA" "code" "com.visualstudio.code" "/usr/share/code/code --unity-launch %F"
    fi 
#modificar para hacerlo mejor
sudo snap install --classic eclipse
sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace "$MATERIA" "eclipse" "/snap/eclipse/67/icon.xpm" "env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/eclipse_eclipse.desktop /snap/bin/eclipse %f"
    
fi
killall progreso
