#!/bin/bash
MATERIA="objetos-1-noche"

rm -rf /home/$MATERIA/.local/share/Trash/* 
find /home/$MATERIA/Escritorio/* -user $MATERIA -exec rm -rf {} \;

echo "Instalaciónd e programas para la materia"
if [[ $UID != 0 ]]; then
        echo "No es administrador"
exit 1
else
    sudo /opt/conejo-blanco/effective-spork/Sistema/usuarios/administrador
    sudo /opt/conejo-blanco/effective-spork/Sistema/usuarios/root
    if [ -f /home/$MATERIA/wollok/wollok ];
    then
        echo "├─Wollok-noche: $(tput setaf 2)OK$(tput sgr 0)"
    else
        echo "├─Wollok-noche: $(tput setaf 1)NO$(tput sgr 0)"
        if [ ! -f /opt/conejo-blanco/Descargas/wollok-linux.gtk.x86_64.zip ];
        then
            sudo wget http://wollokdownload.s3-website-us-west-2.amazonaws.com/wollok/products/stable/wollok-linux.gtk.x86_64.zip -O /opt/conejo-blanco/Descargas/wollok-linux.gtk.x86_64.zip
        fi
        unzip /opt/conejo-blanco/Descargas/wollok-linux.gtk.x86_64.zip -d /home/$MATERIA/wollok
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
        sed -i '1 i\/usr/lib/jvm/java-8-openjdk-amd64/jre/bin' /home/$MATERIA/wollok/wollok.ini
        sed -i '1 i\-vm' /home/$MATERIA/wollok/wollok.ini
        sudo chown -R $MATERIA /home/$MATERIA/wollok/
        sudo chgrp -R $MATERIA /home/$MATERIA/wollok/
        sudo sed -i "8 s|^|# |" /etc/java-8-openjdk/accessibility.properties
        sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace $MATERIA "Wollok" "/home/$MATERIA/wollok/icon.xpm" "/home/$MATERIA/wollok/wollok"
    fi
    node --version >/dev/null
    if [ "$?" = "0" ]; then
    	echo "├─NodeJs:  $(tput setaf 2)OK$(tput sgr 0)"
    else
        echo "├─NodeJs: $(tput setaf 1)NO$(tput sgr 0)"
    fi 
    yarn --version >/dev/null
    if [ "$?" = "0" ]; then
	    echo "├─Yarn:  $(tput setaf 2)OK$(tput sgr 0)"
    else
        echo "├─Yarn: $(tput setaf 1)NO$(tput sgr 0)"
        curl https://deb.nodesource.com/setup_10.x >> /opt/conejo-blanco/Descargas/setup_10.x
        bash /opt/conejo-blanco/Descargas/setup_10.x
        sudo apt-get install -y nodejs
        curl https://dl.yarnpkg.com/debian/pubkey.gpg >> /opt/conejo-blanco/Descargas/pubkey.gpg
        sudo apt-key add /opt/conejo-blanco/Descargas/pubkey.gpg
        sudo echo "deb https://dl.yarnpkg.com/debian/ stable main" >> /etc/apt/sources.list.d/yarn.list
        sudo apt-get update
        sudo apt-get install -y yarn
    fi
    which code >/dev/null
    if [ "$?" = "0" ]; then
	    echo "├─Code Studio:  $(tput setaf 2)OK$(tput sgr 0)"
        if [ ! -f /home/$MATERIA/Escritorio/code.desktop ];
        then
            sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace "$MATERIA" "code" "com.visualstudio.code" "/usr/share/code/code --unity-launch %F"
        fi
    else
        echo "├─Code Studio: $(tput setaf 1)NO$(tput sgr 0)"
        if [ ! -f /opt/conejo-blanco/Descargas/code_1.35.1-1560350270_amd64.deb ];
        then
            sudo wget https://az764295.vo.msecnd.net/stable/c7d83e57cd18f18026a8162d042843bda1bcf21f/code_1.35.1-1560350270_amd64.deb -O /opt/conejo-blanco/Descargas/code_1.35.1-1560350270_amd64.deb
        fi
        sudo dpkg -i /opt/conejo-blanco/Descargas/code_1.35.1-1560350270_amd64.deb
        sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace "$MATERIA" "code" "com.visualstudio.code" "/usr/share/code/code --unity-launch %F"
    fi
fi
