#!/bin/bash

MATERIA="org-comp"
echo -en "\033]0;$MATERIA\a"
rm -rf /home/$MATERIA/.local/share/Trash/*
find /home/$MATERIA/Escritorio/* -user $MATERIA -exec rm -rf {} \;
/usr/bin/progreso &
detach %+ # or % + the number in brackets printed after the above
echo "Instalaciónd e programas para la materia"
if [[ $UID != 0 ]]; then
        echo "No es administrador"
exit 1
else
    sudo /opt/conejo-blanco/effective-spork/Sistema/usuarios/administrador
    sudo /opt/conejo-blanco/effective-spork/Sistema/usuarios/root
    echo "┌──Organizacion de computadoras───╸"
    if [ -f /home/$MATERIA/Logisim/logisim-generic-2.7.1.jar ];
    then
        echo "├─Logisim: $(tput setaf 2)OK$(tput sgr 0)"
        if [ ! -f /home/$MATERIA/Escritorio/logisim.desktop ];
        then
            sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace "$MATERIA" "logisim" "/home/org-comp/Logisim/Logisim-icon.png" "/usr/lib/jvm/java-8-openjdk-amd64/bin/java -jar /home/$MATERIA/Logisim/logisim-generic-2.7.1.jar" 
        fi
        if [ ! -f /home/$MATERIA/Logisim/Logisim-icon.png ];
        then
            wget https://www.dropbox.com/s/fwl7h6g5avnfven/Logisim-icon.png -O /home/$MATERIA/Logisim/Logisim-icon.png
            sudo chmod 555 /home/$MATERIA/Logisim/Logisim-icon.png
            sudo chmod 755 /home/$MATERIA/Logisim/logisim-generic-2.7.1.jar
        fi
    else
        echo "├─Logisim: $(tput setaf 1)NO$(tput sgr 0)"
   	    if [ ! -d /home/$MATERIA/Logisim/ ];
            then
                sudo mkdir /home/$MATERIA/Logisim
                sudo chown $MATERIA /home/$MATERIA/Logisim
                sudo chgrp $MATERIA /home/$MATERIA/Logisim
        fi 
        wget https://razaoinfo.dl.sourceforge.net/project/circuit/2.7.x/2.7.1/logisim-generic-2.7.1.jar -O /home/$MATERIA/Logisim/logisim-generic-2.7.1.jar
        sudo chmod 755 /home/$MATERIA/Logisim/logisim-generic-2.7.1.jar
        wget https://www.dropbox.com/s/fwl7h6g5avnfven/Logisim-icon.png -O /home/$MATERIA/Logisim/Logisim-icon.png
        sudo chmod 555 /home/$MATERIA/Logisim/Logisim-icon.png
        sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace "$MATERIA" "logisim" "/home/org-comp/Logisim/Logisim-icon.png" "/usr/lib/jvm/java-8-openjdk-amd64/bin/java -jar /home/$MATERIA/Logisim/logisim-generic-2.7.1.jar"
    fi
    #sudo sed -i "s/^assistive_technologies=/#&/" /etc/java-11-openjdk/accessibility.properties
   # sudo sed -i "s/^assistive_technologies=/#&/" /etc/java-8-openjdk/accessibility.properties
fi
killall progreso
