#!/bin/bash
MATERIA="persistencia"
echo -en "\033]0;$MATERIA\a"
rm -rf /home/$MATERIA/.local/share/Trash/* 
find /home/$MATERIA/Escritorio/* -user $MATERIA -exec rm -rf {} \;
/usr/bin/progreso &
detach %+ # or % + the number in brackets printed after the above
echo "Instalaciónd e programas para la materia"
if [[ $UID != 0 ]]; then
        echo "No es administrador"
exit 1
else
    sudo /opt/conejo-blanco/effective-spork/Sistema/usuarios/administrador
    sudo /opt/conejo-blanco/effective-spork/Sistema/usuarios/root
    sudo adduser $MATERIA sudo
    ###### 16 de octubre
    sudo groupadd docker
    sudo usermod -aG docker $MATERIA
    #newgrp docker
    ######
    echo "┌──Estructuras de persistencia───╸"
    if [ -f /opt/lampp/manager-linux-x64.run ];
    then
        echo "├─XAMPP: $(tput setaf 2)OK$(tput sgr 0)"
        if [ ! -f /home/$MATERIA/Escritorio/XAMPP.desktop ];
        then
            sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace $MATERIA XAMPP "/opt/lampp/htdocs/favicon.ico" "pkexec /opt/lampp/manager-linux-x64.run"
        fi
    else
        echo "├─XAMPP: $(tput setaf 1)NO$(tput sgr 0)"
        sudo wget https://www.dropbox.com/s/ovd3mtx7ukevts1/com.ubuntu.pkexec.xampp.policy -O /usr/share/polkit-1/actions/com.ubuntu.pkexec.xampp.policy
        sudo wget https://www.apachefriends.org/xampp-files/7.2.6/xampp-linux-x64-7.2.6-0-installer.run -O /opt/conejo-blanco/Descargas/xampp-linux-x64-7.2.6-0-installer.run
        sudo chmod +x /opt/conejo-blanco/Descargas/xampp-linux-x64-7.2.6-0-installer.run
        sudo /opt/conejo-blanco/Descargas/xampp-linux-x64-7.2.6-0-installer.run
        sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace $MATERIA XAMPP "/opt/lampp/htdocs/favicon.ico" "pkexec /opt/lampp/manager-linux-x64.run"
    fi
    nodejs --version >/dev/null
    if [ "$?" = "0" ]; then
	    echo "├─NodeJs:  $(tput setaf 2)OK$(tput sgr 0)"
    else
        echo "├─NodeJs: $(tput setaf 1)NO$(tput sgr 0)"
        sudo apt-get install -y nodejs
    fi
    npm -v >/dev/null
    if [ "$?" = "0" ]; then
	    echo "├─npm:  $(tput setaf 2)OK$(tput sgr 0)"
    else
        echo "├─npm: $(tput setaf 1)NO$(tput sgr 0)"
        sudo apt-get install -y npm
        sudo npm install -g npm
    fi
    which g++ >/dev/null
    if [ "$?" = "0" ]; then
	    echo "├─g++:  $(tput setaf 2)OK$(tput sgr 0)"
    else
        echo "├─g++: $(tput setaf 1)NO$(tput sgr 0)"
        sudo apt-get install -y g++
    fi
    which gcc >/dev/null
    if [ "$?" = "0" ]; then
	    echo "├─gcc:  $(tput setaf 2)OK$(tput sgr 0)"
    else
        echo "├─gcc: $(tput setaf 1)NO$(tput sgr 0)"
        sudo apt-get install -y gcc
    fi
    which make >/dev/null
    if [ "$?" = "0" ]; then
	    echo "├─make:  $(tput setaf 2)OK$(tput sgr 0)"
    else
        echo "├─make: $(tput setaf 1)NO$(tput sgr 0)"
        sudo apt-get install -y make
    fi
    echo "└────────────────────────╸"
fi
killall progreso
