#!/bin/bash
MATERIA="sig"
echo -en "\033]0;$MATERIA\a"
rm -rf /home/$MATERIA/.local/share/Trash/*
find /home/$MATERIA/Escritorio/* -user $MATERIA -exec rm -rf {} \;
/usr/bin/progreso &
echo "Instalaciónd e programas para la materia"
if [[ $UID != 0 ]]; then
        echo "No es administrador"
        exit 1
else
    sudo /opt/conejo-blanco/effective-spork/Sistema/usuarios/administrador
    sudo /opt/conejo-blanco/effective-spork/Sistema/usuarios/root
    #### Aca van las cosas

    which qgis >/dev/null
    if [ "$?" = "0" ]; then
    	echo "├─QGIS:  $(tput setaf 2)OK$(tput sgr 0)"
    else
		sudo apt -y install gnupg software-properties-common
		wget -qO - https://qgis.org/downloads/qgis-2021.gpg.key | sudo gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/qgis-archive.gpg --import
		sudo chmod a+r /etc/apt/trusted.gpg.d/qgis-archive.gpg
		sudo add-apt-repository "deb https://qgis.org/ubuntu $(lsb_release -c -s) main"
		sudo apt update
		sudo apt -y install qgis qgis-plugin-grass

    fi
    if [ ! -f /home/$MATERIA/Escritorio/QGIS.desktop ];
    then
        sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace $MATERIA "QGIS" "qgis" "qgis %F"
    fi
    
    #RStudio
    which rstudio >/dev/null
    if [ "$?" = "0" ]; then
    	echo "├─RStudio:  $(tput setaf 2)OK$(tput sgr 0)"
    else
		sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
        sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/'
        sudo apt-get install -y r-base r-base-dev
        R --version
        wget https://download1.rstudio.org/desktop/bionic/amd64/rstudio-2022.02.3-492-amd64.deb  -O /opt/conejo-blanco/Descargas/rstudio.deb
        sudo dpkg -i /opt/conejo-blanco/Descargas/rstudio.deb 
        sudo apt --fix-broken install -y
	sudo R CMD javareconf

    fi
    if [ ! -f /home/$MATERIA/Escritorio/RStudio.desktop ];
    then
        sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace $MATERIA "RStudio" "rstudio" "rstudio %F"
    fi
    sudo R CMD javareconf
    sudo apt -y install libgdal-dev
    
fi
killall progreso
