#!/bin/bash
MATERIA="taller-c"
echo -en "\033]0;$MATERIA\a"
rm -rf /home/$MATERIA/.local/share/Trash/* 

echo "Instalaciónd e programas para la materia"
if [[ $UID != 0 ]]; then
        echo "No es administrador"
exit 1
else
    sudo /opt/conejo-blanco/effective-spork/Sistema/usuarios/administrador
    sudo /opt/conejo-blanco/effective-spork/Sistema/usuarios/root
    which dotnet >/dev/null
    if [ "$?" = "0" ]; then
	    echo "├─Dotnet:  $(tput setaf 2)OK$(tput sgr 0)"
    else
        echo "Instalaciónd e programas para la materia"
#        sudo mkdir /opt/conejo-blanco/Descargas
        sudo wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O /opt/conejo-blanco/Descargas/packages-microsoft-prod.deb
        sudo dpkg -i /opt/conejo-blanco/Descargas/packages-microsoft-prod.deb
        if [ "$?" = "0" ]; then
            sudo add-apt-repository universe
            sudo apt-get update
            sudo apt-get -y install apt-transport-https
            sudo apt-get update
            sudo apt-get -y install dotnet-sdk-3.0
        else
            zenity --warning --text "Atención: DPKG ocupado, por favor reiniciar."
                systemctl reboot    
        fi
    fi
    which code >/dev/null
    if [ "$?" = "0" ]; then
    	echo "├─Code Studio:  $(tput setaf 2)OK$(tput sgr 0)"
    else
        echo "├─Code Studio: $(tput setaf 1)NO$(tput sgr 0)"
        sudo wget https://az764295.vo.msecnd.net/stable/c7d83e57cd18f18026a8162d042843bda1bcf21f/code_1.35.1-1560350270_amd64.deb -O /opt/conejo-blanco/Descargas/code_1.35.1-1560350270_amd64.deb
        sudo dpkg -i /opt/conejo-blanco/Descargas/code_1.35.1-1560350270_amd64.deb
        sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace "$MATERIA" "code" "com.visualstudio.code" "/usr/share/code/code --unity-launch %F"
    fi
fi
