#!/bin/bash

limpiar () {
    if [ -d /home/$1/Descargas/ ];
       then
            echo "Limpiando $1 2020"
            rm -rf /home/$1/Descargas/*
            rm -rf /home/$1/Documentos/*
            rm -rf /home/$1/Imágenes/*
            rm -rf /home/$1/Vídeos/*
            rm -rf /home/$1/Música/*
    fi
}

MATERIA="usuario-invitado"
echo -en "\033]0;$MATERIA\a"
rm -rf /home/$MATERIA/.local/share/Trash/* 
limpiar usuario-invitado
find /home/$MATERIA/Escritorio/* -user $MATERIA -exec rm -rf {} \;
/usr/bin/progreso &
detach %+ # or % + the number in brackets printed after the above
echo "Instalaciónd e programas para la materia"
if [[ $UID != 0 ]]; then
        echo "No es administrador"
exit 1
else
    sudo /opt/conejo-blanco/effective-spork/Sistema/usuarios/administrador
    sudo /opt/conejo-blanco/effective-spork/Sistema/usuarios/root
    sudo passwd -d usuario-invitado
    sudo passwd -d nuevos-entornos
    sudo passwd -d martin-vernengo
    #if [ ! -f /home/$MATERIA/Escritorio/firefox.desktop ];
    #then
        sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace $MATERIA "firefox" "firefox" "firefox --private-window http://unahur.edu.ar"
    #fi
    which google-chrome-stable >/dev/null
    if [ "$?" = "0" ]; then
    	echo "├─Chrome:  $(tput setaf 2)OK$(tput sgr 0)"
    else
        echo "├─Chrome: $(tput setaf 1)NO$(tput sgr 0)"
        sudo wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -O /opt/conejo-blanco/Descargas/google-chrome-stable_current_amd64.deb
        sudo dpkg -i /opt/conejo-blanco/Descargas/google-chrome-stable_current_amd64.deb
    fi
    #if [ ! -f /home/$MATERIA/Escritorio/google-chrome.desktop ];
    #then
        sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace $MATERIA "google-chrome" "google-chrome" "google-chrome --password-store=basic --incognito http://unahur.edu.ar"
    #fi
    
    if [ -f /home/$MATERIA/Logisim/logisim-generic-2.7.1.jar ];
    then
        echo "├─Logisim: $(tput setaf 2)OK$(tput sgr 0)"
        if [ ! -f /home/$MATERIA/Escritorio/logisim.desktop ];
        then
            sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace "$MATERIA" "logisim" "/home/$MATERIA/Logisim/Logisim-icon.png" "/usr/lib/jvm/java-8-openjdk-amd64/bin/java -jar /home/$MATERIA/Logisim/logisim-generic-2.7.1.jar" 
        fi
        if [ ! -f /home/$MATERIA/Logisim/Logisim-icon.png ];
        then
            wget https://www.dropbox.com/s/fwl7h6g5avnfven/Logisim-icon.png -O /home/$MATERIA/Logisim/Logisim-icon.png
            sudo chmod 555 /home/$MATERIA/Logisim/Logisim-icon.png
            sudo chmod 755 /home/$MATERIA/Logisim/logisim-generic-2.7.1.jar
        fi
    else
        echo "├─Logisim: $(tput setaf 1)NO$(tput sgr 0)"
   	    if [ ! -d /home/$MATERIA/Logisim/ ];
            then
                sudo mkdir /home/$MATERIA/Logisim
                sudo chown $MATERIA /home/$MATERIA/Logisim
                sudo chgrp $MATERIA /home/$MATERIA/Logisim
        fi 
        wget https://razaoinfo.dl.sourceforge.net/project/circuit/2.7.x/2.7.1/logisim-generic-2.7.1.jar -O /home/$MATERIA/Logisim/logisim-generic-2.7.1.jar
        sudo chmod 755 /home/$MATERIA/Logisim/logisim-generic-2.7.1.jar
        wget https://www.dropbox.com/s/fwl7h6g5avnfven/Logisim-icon.png -O /home/$MATERIA/Logisim/Logisim-icon.png
        sudo chmod 555 /home/$MATERIA/Logisim/Logisim-icon.png
        sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace "$MATERIA" "logisim" "/home/$MATERIA/Logisim/Logisim-icon.png" "/usr/lib/jvm/java-8-openjdk-amd64/bin/java -jar /home/$MATERIA/Logisim/logisim-generic-2.7.1.jar"
    fi
    if [ ! -f /home/$MATERIA/Escritorio/Apagar.desktop ];
    then
        sudo bash /opt/conejo-blanco/effective-spork/Sistema/utilitarios/crea_enlace $MATERIA "Apagar" "system-shutdown" "conejo-blanco -x"
    fi
    sudo apt-get -y update
    sudo apt-get -y autoremove
    sudo apt-get -y upgrade
    sudo apt-get -y install gimp
    sudo dpkg --configure -a
fi
killall progreso
