#!/bin/bash
if [[ $UID != 0 ]]; then
    for n in {1..5}; do
        notify-send 'NO dijiste la palabra mágica...'
        echo "NO dijiste la palabra mágica..."
        echo ""
        sleep 1
            
    done   
    echo "please start the script as root or sudo"
exit 1
else
    cd /opt/conejo-blanco/effective-spork
    VAR=$((git fetch -v --dry-run) 2>&1)
    if [[ $VAR = POST* ]]
    then
	    echo "Repositorio no actualizado"
            sudo git pull origin master
            pkexec bash /opt/conejo-blanco/effective-spork/Ejecutame
    else
	    echo "Nada que actualizar"
    fi
fi
