#!/bin/bash

#/opt/conejo-blanco/effective-spork
#/usr/bin/conejo-blanco

source /opt/conejo-blanco/effective-spork/utiles.sh

sudo /opt/conejo-blanco/effective-spork/Sistema/usuarios/administrador
# chequeo y creacion de usuarios
existeuservf "algebra-1"
existeuservf "base-datos"
existeuservf "estadistica"
existeuservf "persistencia"
existeuservf "estruc-datos"
existeuservf "interfaces-usuario"
existeuservf "intro-prog"
existeuservf "nuevos-entornos"
existeuservf "objetos-1-noche"
existeuservf "objetos-1-tarde"
existeuservf "objetos-2"
existeuservf "org-comp"
existeuservf "redes"
existeuservf "sist-operativos"
existeuservf "ing-software"
existeuservf "arduino"
existeuservf "bioinformatica"
existeuservf "biotecnologia"
# Lunes 30 de septiembre de 2019
existeuservf "taller-c"

# martes 10 de septiembre de 2019
# notify-send 'ATENCION' 'A partir de ahora cualquier archivo personal debe ir en Documentos de la carpeta personal' -u normal -i 'conejo-blanco' -t 10000
pkexec bash /opt/conejo-blanco/effective-spork/Sistema/sescritorios

## actulización del bienvenida-unahur
killall bienvenida-unahur
sudo cp /opt/conejo-blanco/effective-spork/project1 /usr/bin/bienvenida-unahur
sudo cp /opt/conejo-blanco/effective-spork/Sistema/cb-2409 /usr/bin/conejo-blanco
sudo chmod 755 /usr/bin/bienvenida-unahur
# bienvenida-unahur
sudo rm /snap/bin/ubuntu-mate-welcome

descargar_logosvf
crea_autoejecutablevf logo "gsettings set org.mate.background picture-filename '/usr/share/backgrounds/Logo.jpg'"
crea_autoejecutablevf paneles "mate-panel --reset"
crea_autoejecutablevf interfaz "gsettings reset-recursively org.mate.interface"
crea_autoejecutablevf marquitos "gsettings reset-recursively org.mate.Marco"
crea_autoejecutablevf protector "gsettings reset-recursively org.mate.screensaver"
protector_pantallavf
montar_fstabvf "sda3" "ntfs-3g" "DATOS"

