#!/bin/bash

#/opt/conejo-blanco/effective-spork
#/usr/bin/conejo-blanco

source /opt/conejo-blanco/effective-spork/utiles.sh

sudo /opt/conejo-blanco/effective-spork/Sistema/usuarios/administrador
# chequeo y creacion de usuarios
existeuservf "algebra-1"
existeuservf "base-datos"
existeuservf "estadistica"
existeuservf "persistencia"
existeuservf "estruc-datos"
existeuservf "interfaces-usuario"
existeuservf "intro-prog"
existeuservf "nuevos-entornos"
existeuservf "objetos-1-noche"
existeuservf "objetos-1-tarde"
existeuservf "objetos-2"
existeuservf "org-comp"
existeuservf "redes"
existeuservf "sist-operativos"
existeuservf "ing-software"
existeuservf "arduino"
existeuservf "bioinformatica"
existeuservf "biotecnologia"
# Lunes 30 de septiembre de 2019
existeuservf "taller-c"

# martes 10 de septiembre de 2019
# notify-send 'ATENCION' 'A partir de ahora cualquier archivo personal debe ir en Documentos de la carpeta personal' -u normal -i 'conejo-blanco' -t 10000
pkexec bash /opt/conejo-blanco/effective-spork/Sistema/sescritorios

## actulización del bienvenida-unahur
killall bienvenida-unahur
sudo cp /opt/conejo-blanco/effective-spork/Sistema/project1 /usr/bin/bienvenida-unahur
sudo chmod 755 /usr/bin/bienvenida-unahur
sudo cp /opt/conejo-blanco/effective-spork/Sistema/cb /usr/bin/conejo-blanco
sudo chmod 755 /usr/bin/conejo-blanco
sudo cp /opt/conejo-blanco/effective-spork/Sistema/progreso /usr/bin/progreso
sudo chmod 755 /usr/bin/progreso
sudo cp /opt/conejo-blanco/effective-spork/Sistema/palabramagica /usr/bin/palabramagica
sudo chmod 755 /usr/bin/palabramagica
sudo cp /opt/conejo-blanco/effective-spork/Sistema/ocultador /usr/bin/ocultador
sudo chmod 755 /usr/bin/ocultador
# bienvenida-unahur
sudo rm /snap/bin/ubuntu-mate-welcome

descargar_logosvf
crea_autoejecutablevf logo "gsettings set org.mate.background picture-filename '/usr/share/backgrounds/Logo.jpg'"
crea_autoejecutablevf paneles "mate-panel --reset"
crea_autoejecutablevf interfaz "gsettings reset-recursively org.mate.interface"
crea_autoejecutablevf marquitos "gsettings reset-recursively org.mate.Marco"
sudo rm /etc/xdg/autostart/protector.desktop
crea_autoejecutablevf protector "gsettings reset-recursively org.mate.screensaver | gsettings set org.mate.screensaver lock-enabled false"
crea_autoejecutablevf bienvenida-unahur "/usr/bin/bienvenida-unahur"
protector_pantallavf
montar_fstabvf "sda3" "ntfs-3g" "DATOS"
sudo mkdir -p /opt/conejo-blanco/Descargas
sudo sed -i '16,$d' /etc/crontab

sudo apt-get autoremove -y
sudo rm -rf /opt/conejo-blanco/Descargas/*
echo 2 | sudo update-alternatives --config java
#bienvenida-unahur
sudo sed -i "s/^assistive_technologies=/#&/" /etc/java-11-openjdk/accessibility.properties
sudo sed -i "s/^assistive_technologies=/#&/" /etc/java-8-openjdk/accessibility.properties

