#!/bin/bash
VERSION="3.08.16"
# nombre de terminal
echo -en "\033]0;Conejo-Blanco\a"
#Opciones
while getopts "aheu:vd" OPTION; do
        case $OPTION in

                e)
                        pkexec bash /opt/conejo-blanco/effective-spork/Ejecutame
                        exit 0
                        ;;
                h)
                        echo "Para ayuda preguntar en el Instituto de Tecnologia e Ingeniería - UNAHUR"
                        exit 0
                        ;;
                a)
                        pkexec bash /opt/conejo-blanco/effective-spork/Actualizame
                        exit 0
                        ;;
                u)
                        pkexec bash /opt/conejo-blanco/effective-spork/Materias/Programas/$OPTARG
                        exit 0
                        ;;
                v)
                        echo "versión: $VERSION"
                        exit 0
                        ;;
                d)
                        pkexec bash /opt/conejo-blanco/effective-spork/Sistema/vDesc
                        exit 0
                        ;;        
                x)
                        pkexec bash /opt/conejo-blanco/effective-spork/Sistema/Apagame
                        exit 0
                        ;;     
        esac
done
#verifica sudo
if [[ $UID != 0 ]]; then
        notify-send 'NO dijiste la palabra mágica...'  
        echo "Solo el administrador puede ejecutar este comando"
        palabramagica &
        exit
exit 0
else
    /usr/bin/ocultador &
    echo "FUNCIONO, todo está apagado pero funcionó."        
    notify-send 'Universidad Nacional de Hurlingham' 'Laboratorio de Informática' -u normal -i 'UNAHUR-logo' -t 10000
    pkexec bash /opt/conejo-blanco/effective-spork/Actualizame
fi
