#!/bin/bash
VERSION="1.11.02"
# nombre de terminal
echo -en "\033]0;Conejo-Blanco\a"
#Opciones
while getopts "aheu:vd" OPTION; do
        case $OPTION in

                e)
                        pkexec bash /opt/conejo-blanco/effective-spork/Ejecutame
                        exit 0
                        ;;
                h)
                        echo "Para ayuda preguntar en el Instituto de Tecnologia e Ingeniería - UNAHUR"
                        exit 0
                        ;;
                a)
                        pkexec bash /opt/conejo-blanco/effective-spork/Actualizame
                        exit 0
                        ;;
                u)
                        pkexec bash /opt/conejo-blanco/effective-spork/Materias/Programas/$OPTARG
                        exit 0
                        ;;
                v)
                        echo "versión: $VERSION"
                        exit 0
                        ;;
                d)
                        if [ "$(ls -A /opt/conejo-blanco/Descargas)" ]; then
                        echo "La carpeta de descargas no está vacía"
                        du -h /opt/conejo-blanco/Descargas | cut -f -1
                        read -p "¿Vaciarla? [S/s]" -n 1 -r
                        echo    # (optional) move to a new line
                        if [[ $REPLY =~ ^[Ss]$ ]]
                            then
                                pkexec bash /opt/conejo-blanco/effective-spork/Sistema/vDesc
                                exit 1
                        fi
                        else
                            echo "La carpeta de descargas está vacía"
                        fi
                        exit 0
                        ;;                    
        esac
done
#verifica sudo
if [[ $UID != 0 ]]; then
        notify-send 'NO dijiste la palabra mágica...'  
        echo "Solo el administrador puede ejecutar este comando"
        palabramagica &
        exit
exit 0
else
    echo "FUNCIONO, todo está apagado pero funcionó."        
    notify-send 'Universidad Nacional de Hurlingham' 'Laboratorio de Informática' -u normal -i 'UNAHUR-logo' -t 10000
    pkexec bash /opt/conejo-blanco/effective-spork/Actualizame
fi
