#!/bin/bash

limpiar () {
    if [ -d /home/$1/Descargas/ ];
       then
            echo "Limpiando $1 2020"
            rm -rf /home/$1/Descargas/*
            rm -rf /home/$1/Documentos/*
            rm -rf /home/$1/Imágenes/*
            rm -rf /home/$1/Vídeos/*
            rm -rf /home/$1/Música/*
    fi
}
echo "Limpieza 2020"
limpiar "algebra-1"
limpiar "arduino"
limpiar "base-datos"
limpiar "bioinformatica"
limpiar "biotecnologia"
limpiar "cidia"
limpiar "concurrente"
limpiar "estadistica"
limpiar "estruc-datos"
limpiar "ing-software"
limpiar "interfaces-usuario"
limpiar "intro-prog"
limpiar "nuevos-entornos"
limpiar "objetos-1-tarde"
limpiar "objetos-1-noche"
limpiar "objetos-2"
limpiar "org-comp"
limpiar "persistencia"
limpiar "redes"
limpiar "sist-operativos"
limpiar "taller-c"
